#!/bin/bash

#Prepare runing code

#server="server"
#client="client"

numNode=$1
num_clients=$2
num_tasks=$3
sleep_time=$4
mode=$5
max_tasks_per_package=$6
logging=$7
prefix=$8
shared=$9
nfile=${10}
DAG_choice=${11}
num_cores=${12}
monitor_interval=${13}

ip=`ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
port1=50000

export IP=$ip
export NNODE=$numNode
export PORT_FOR_REPLICA=50009


matrix_home=/home/ubuntu/mnt/matrix_1/matrix
workload_home=/home/ubuntu/mnt/hw
#echo $ip
#compare local ip with first ip in neighbor_$numNode
#read line < $nfile
#firstip=`echo $line | awk '{print $1}'`
#firstport=`echo $line | awk '{print $2}'`
#echo "firstip is $firstip"
#echo "firstport is $firstport"

declare -a client_list
for ((i=1;i<=$num_clients;i++))
do
client_list[$i]=`cat $nfile | awk NR==$i | awk {'print $1'}`
done

per_client_task=$(($num_tasks/$num_clients))

echo $per_client_tasks

declare -i index
for ((i=1;i<=$num_clients;i++))
do
if [ "$ip" == "${client_list[$i]}" ]
then
index=$(($i-1))
echo "match execute client $i $ip ${client_list[$i]} numtasks = $num_tasks"
$matrix_home/client $per_client_task $nfile $matrix_home/zht.cfg TCP $sleep_time $mode $max_tasks_per_package $i $num_tasks $prefix $shared $DAG_choice $num_cores $monitor_interval $workload_home/workload$numNode/workload$index &
fi
done

#if [ "$ip" = "$firstip" ]
#then
#echo "firstip is $firstip"
#echo "match execute client $ip $firstip"
#sleep 60
#cout << "Usage: " << argv[0] << "\tnum_tasks\tneighborlist_file\tzht_config_file\tprotocol[TCP/UDP]\tsleep_time\tsubmissionmode[0/1/2]\tmax_tasks_per_package" << endl;
#/export/home/arajend/$client $num_tasks $nfile /export/home/arajend/zht.cfg TCP $sleep_time $mode $max_tasks_per_package $prefix $shared &
#echo "client started at $ip"
#fi
#else
#echo "nomatch execute server $ip"
#cout << "Usage: " << argv[0] << "\tserver_port_no\tneighbor_file\tconfig_file\tProtocol[TCP/UDP]\tUsername\tLogging[0/1]\tmax_tasks_per_package" << endl;
#rm /tmp/log_server

#echo "$matrix_home/server $port1 $nfile $matrix_home/zht.cfg TCP kwangiit 0 $max_tasks_per_package $num_tasks $prefix $shared $num_cores $monitor_interval" >> /tmp/log_server
#echo ""

$matrix_home/server $port1 $nfile $matrix_home/zht.cfg TCP ubuntu 0 $max_tasks_per_package $num_tasks $prefix $shared $num_cores $monitor_interval

#/export/home/arajend/$server $port2 /export/home/arajend/neighbor_$numNode /export/home/arajend/zht.cfg TCP anupam $logging $max_tasks_per_package &
#fi

#echo "end of script"

